// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanHang.Models;

namespace WebBanHang.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250522080456_images")]
    partial class images
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebBanHang.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Điện thoại"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Máy tính bảng"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Laptop"
                        });
                });

            modelBuilder.Entity("WebBanHang.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImageUrl = "images/products/f4b64997-abfc-428e-ac53-2f58f4a022aa.jpg",
                            Name = "Iphone 7",
                            Price = 300.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ImageUrl = "images/products/559e0fa1-fce5-41ae-82c5-ad38b1fe92f8.jpg",
                            Name = "Iphone 7s",
                            Price = 350.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ImageUrl = "images/products/56ae225d-7c00-405f-b4a1-9b6193888789.jpg",
                            Name = "Iphone 8",
                            Price = 400.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ImageUrl = "images/products/bf448f8c-9d1c-40d9-a61f-4bc3b0078540.jpg",
                            Name = "Iphone 8s",
                            Price = 420.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            ImageUrl = "images/products/fca9f033-0ded-4e27-84b0-d0e027b5d03d.jpg",
                            Name = "Iphone 12",
                            Price = 630.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            ImageUrl = "images/products/115934e4-92c5-492d-84ff-0c2852f3ba3c.jpg",
                            Name = "Iphone 12 Pro",
                            Price = 750.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            ImageUrl = "images/products/dd2e787a-3b40-440e-930b-eab3e3a00c06.jpg",
                            Name = "Iphone 14",
                            Price = 820.0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            ImageUrl = "images/products/93b0478f-18d7-42b4-9ffd-e8658cbfbe7f.jpg",
                            Name = "Iphone 14 Pro",
                            Price = 950.0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            ImageUrl = "images/products/9f71f0bf-7585-4835-875a-396936c9dca4.jpg",
                            Name = "Iphone 15",
                            Price = 1200.0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            ImageUrl = "images/products/0c7475e1-6507-4df5-89e4-2d6c893f23eb.jpg",
                            Name = "Iphone 15 Pro Max ",
                            Price = 1450.0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            ImageUrl = "images/products/9bae10d4-d035-44eb-9f30-83381a73dd8d.jpg",
                            Name = "Ipad Gen 10",
                            Price = 750.0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            ImageUrl = "images/products/fd40ff16-2beb-43bf-bb66-425b3b598ee4.jpg",
                            Name = "Ipad Pro 11",
                            Price = 1250.0
                        });
                });

            modelBuilder.Entity("WebBanHang.Models.Product", b =>
                {
                    b.HasOne("WebBanHang.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
